# Generated by Django 6.0.6 on 2026-06-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PATIENT', 'Patient'), ('AUDITOR', 'Auditor'), ('INSURER', 'Insurer')], default='PATIENT', max_length=20),
        ),
    ]
