# Generated by Django 6.0.6 on 2026-06-19 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='composer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='authored_compositions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composition',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
