# Generated by Django 6.0.6 on 2026-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype_id', models.CharField(default='openEHR-EHR-OBSERVATION.vital_signs.v1', help_text='e.g., openEHR-EHR-OBSERVATION.pulse.v2', max_length=255)),
                ('element_code', models.CharField(help_text='e.g., heart_rate, body_temperature', max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='critical', max_length=20)),
                ('alert_message_template', models.TextField(help_text='Custom string token. Use {value} and {bound} for dynamic injection.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
