# Generated by Django 6.0.6 on 2026-06-18 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
